# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile basic LaTeX document
        uses: ./
        with:
          root_file: test.tex
          working_directory: test/
      - name: Compile LaTeX document with pre/post compile actions
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          post_compile: |
            ls test.pdf
